In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("cpdata.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  3100 non-null   float64
 1   humidity     3100 non-null   float64
 2   ph           3100 non-null   float64
 3   rainfall     3100 non-null   float64
 4   label        3100 non-null   object
dtypes: float64(4), object(1)
memory usage: 121.2+ KB

In [19]:
df.label.value_counts() # checks balanced number of samples

label
rice            100
Moth Beans      100
pomegranate     100
papaya          100
orange          100
muskmelon       100
mango           100
apple           100
grapes          100
banana          100
Chickpea        100
Pigeon Peas     100
Adzuki Beans    100
Black gram      100
Coconut         100
Kidney Beans    100
wheat           100
Tobacco         100
Sugarcane       100
Rubber          100
Peas            100
Ground Nut      100
Cotton          100
Coffee          100
Jute            100
Lentil          100
maize           100
millet          100
Tea             100
Mung Bean       100
watermelon      100
Name: count, dtype: int64

In [34]:
df.head()  #conditions for growing rice

   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
1    21.770462  80.319644  7.038096  226.655537  rice
2    23.004459  82.320763  7.840207  263.964248  rice
3    26.491096  80.158363  6.980401  242.864034  rice
4    20.130175  81.604873  7.628473  262.717340  rice

In [20]:
df.describe()

       temperature     humidity           ph     rainfall
count  3100.000000  3100.000000  3100.000000  3100.000000
mean     27.108466    66.005312     6.368913   110.213031
std       7.566308    24.007713     0.809477    64.048562
min       8.825675    10.034048     3.504752    20.211267
25%      22.810495    55.244920     5.895343    64.909095
50%      26.102848    68.980529     6.342518    97.057093
75%      29.365644    84.446524     6.841616   141.210784
max      54.986760    99.981876     9.935091   397.315380

#### Column separation

In [21]:
X = df.drop('label', axis=1)  #axis =1 is checking for column, axis - 0 is for row 
y = df['label']  # y is dependent, x= independent

#### Data Splitting

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=21, test_size=.25, stratify=y)  #stratify used to maintain 
                                                                                                    # balance in distribution

In [31]:
print(X_train.shape)  #shows rows and columns 2325 rows for X and 4 columns.  775 is 25%
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2325, 4)
(775, 4)
(2325,)
(775,)

In [32]:
2325/3100

0.75

### Algorithms

In [33]:
from sklearn.linear_model import LogisticRegression   ## doing classification not linear regression so logistic classifying based on different conditions
from sklearn.ensemble import RandomForestClassifier

In [36]:
lr = RandomForestClassifier(random_state=20)  #lr is the algorithm we want to train
lr.fit(X_train,y_train)  #when training it provides both features and target
lr_pred = lr.predict(X_test)  # predict with test saves as lr pred

In [38]:
lr_pred

array(['Coffee', 'Cotton', 'Tea', 'Lentil', 'grapes', 'Lentil', 'Lentil',
       'Lentil', 'Coffee', 'mango', 'orange', 'muskmelon', 'grapes',
       'wheat', 'maize', 'apple', 'Jute', 'Tea', 'Tobacco', 'papaya',
       'grapes', 'Rubber', 'watermelon', 'papaya', 'watermelon',
       'Moth Beans', 'mango', 'Moth Beans', 'apple', 'millet',
       'Moth Beans', 'Rubber', 'wheat', 'apple', 'watermelon', 'Peas',
       'Moth Beans', 'watermelon', 'wheat', 'Peas', 'Jute', 'Peas',
       'Moth Beans', 'grapes', 'Jute', 'Pigeon Peas', 'Lentil', 'mango',
       'rice', 'Adzuki Beans', 'Sugarcane', 'Moth Beans', 'Coffee',
       'Rubber', 'Mung Bean', 'mango', 'Coconut', 'Kidney Beans',
       'watermelon', 'Pigeon Peas', 'maize', 'muskmelon', 'Peas',
       'Ground Nut', 'Jute', 'Adzuki Beans', 'Cotton', 'rice', 'wheat',
       'orange', 'apple', 'maize', 'Rubber', 'grapes', 'Coffee',
       'pomegranate', 'pomegranate', 'muskmelon', 'watermelon', 'rice',
       'millet', 'pomegranate', 'Ground Nut', 'pomegranate', 'rice',
       'grapes', 'Cotton', 'papaya', 'Ground Nut', 'muskmelon',
       'Sugarcane', 'Rubber', 'Coffee', 'Lentil', 'Ground Nut',
       'Sugarcane', 'Tobacco', 'grapes', 'Sugarcane', 'Pigeon Peas',
       'Coconut', 'Pigeon Peas', 'Pigeon Peas', 'Sugarcane', 'orange',
       'Tea', 'orange', 'Kidney Beans', 'watermelon', 'grapes',
       'Mung Bean', 'Ground Nut', 'Sugarcane', 'muskmelon', 'grapes',
       'Adzuki Beans', 'maize', 'millet', 'watermelon', 'Coconut',
       'Cotton', 'Jute', 'millet', 'Sugarcane', 'Mung Bean', 'Tea',
       'Chickpea', 'banana', 'Lentil', 'Peas', 'wheat', 'Coconut',
       'muskmelon', 'Pigeon Peas', 'muskmelon', 'Rubber', 'apple',
       'Chickpea', 'orange', 'grapes', 'maize', 'Jute', 'Coffee', 'maize',
       'millet', 'Mung Bean', 'Moth Beans', 'Kidney Beans',
       'Adzuki Beans', 'Coconut', 'Peas', 'Rubber', 'Coconut', 'Cotton',
       'apple', 'Tobacco', 'orange', 'Black gram', 'Mung Bean', 'Coconut',
       'Ground Nut', 'millet', 'Peas', 'watermelon', 'Cotton', 'mango',
       'Lentil', 'Chickpea', 'Tobacco', 'Coconut', 'Peas', 'banana',
       'millet', 'Ground Nut', 'Tea', 'Chickpea', 'wheat', 'Sugarcane',
       'Black gram', 'maize', 'rice', 'Cotton', 'Jute', 'rice', 'Tea',
       'Rubber', 'Rubber', 'Coffee', 'Jute', 'banana', 'Tea',
       'Ground Nut', 'pomegranate', 'Tea', 'apple', 'papaya',
       'Ground Nut', 'Sugarcane', 'watermelon', 'Chickpea', 'wheat',
       'Mung Bean', 'Ground Nut', 'Adzuki Beans', 'Lentil', 'muskmelon',
       'Tea', 'Adzuki Beans', 'Ground Nut', 'rice', 'Kidney Beans', 'Tea',
       'Tea', 'Pigeon Peas', 'Pigeon Peas', 'pomegranate', 'Cotton',
       'Rubber', 'Adzuki Beans', 'rice', 'wheat', 'Cotton', 'Chickpea',
       'Tobacco', 'banana', 'maize', 'Cotton', 'mango', 'Adzuki Beans',
       'Adzuki Beans', 'Cotton', 'Moth Beans', 'millet', 'millet',
       'mango', 'rice', 'banana', 'orange', 'Kidney Beans', 'Tea',
       'Kidney Beans', 'grapes', 'Lentil', 'maize', 'banana', 'Lentil',
       'papaya', 'mango', 'Rubber', 'Pigeon Peas', 'Rubber', 'Jute',
       'orange', 'Lentil', 'Moth Beans', 'orange', 'muskmelon',
       'muskmelon', 'Tobacco', 'Tea', 'Rubber', 'Peas', 'Adzuki Beans',
       'muskmelon', 'Rubber', 'mango', 'Peas', 'Tobacco', 'maize',
       'Tobacco', 'apple', 'Cotton', 'grapes', 'Cotton', 'wheat',
       'watermelon', 'Sugarcane', 'pomegranate', 'rice', 'banana',
       'Kidney Beans', 'banana', 'maize', 'pomegranate', 'grapes',
       'papaya', 'Mung Bean', 'Lentil', 'Coconut', 'Coconut',
       'watermelon', 'grapes', 'apple', 'banana', 'muskmelon',
       'pomegranate', 'Mung Bean', 'watermelon', 'Mung Bean',
       'Moth Beans', 'Coconut', 'Black gram', 'watermelon', 'orange',
       'Moth Beans', 'Tobacco', 'pomegranate', 'Coffee', 'Tea', 'apple',
       'pomegranate', 'papaya', 'Chickpea', 'Cotton', 'grapes', 'banana',
       'Lentil', 'Lentil', 'Chickpea', 'Cotton', 'Coconut', 'banana',
       'millet', 'Chickpea', 'apple', 'Jute', 'watermelon',
       'Kidney Beans', 'Ground Nut', 'pomegranate', 'papaya',
       'Black gram', 'grapes', 'Coconut', 'Jute', 'mango', 'rice',
       'Black gram', 'orange', 'Kidney Beans', 'watermelon',
       'pomegranate', 'Pigeon Peas', 'Black gram', 'Rubber', 'Tea',
       'wheat', 'apple', 'Coffee', 'Tobacco', 'Rubber', 'Kidney Beans',
       'Jute', 'Ground Nut', 'Tea', 'rice', 'wheat', 'Coffee', 'Rubber',
       'millet', 'wheat', 'papaya', 'millet', 'banana', 'rice', 'Coconut',
       'Tea', 'Mung Bean', 'Sugarcane', 'mango', 'Peas', 'Mung Bean',
       'Rubber', 'Tobacco', 'Adzuki Beans', 'millet', 'Ground Nut',
       'muskmelon', 'watermelon', 'Ground Nut', 'Peas', 'banana',
       'Pigeon Peas', 'rice', 'Cotton', 'Cotton', 'Kidney Beans',
       'Sugarcane', 'pomegranate', 'apple', 'Mung Bean', 'watermelon',
       'orange', 'Ground Nut', 'Moth Beans', 'Moth Beans', 'Chickpea',
       'maize', 'muskmelon', 'Coconut', 'orange', 'orange', 'wheat',
       'Tea', 'papaya', 'Chickpea', 'Black gram', 'Pigeon Peas', 'Rubber',
       'Coconut', 'grapes', 'Peas', 'Coconut', 'orange', 'Black gram',
       'papaya', 'Tobacco', 'muskmelon', 'maize', 'Cotton', 'Lentil',
       'Cotton', 'Chickpea', 'Black gram', 'papaya', 'millet',
       'muskmelon', 'Pigeon Peas', 'Black gram', 'Lentil', 'Black gram',
       'Black gram', 'wheat', 'Kidney Beans', 'Coffee', 'maize', 'banana',
       'Adzuki Beans', 'wheat', 'Tobacco', 'watermelon', 'Mung Bean',
       'Coconut', 'Lentil', 'Kidney Beans', 'Cotton', 'Moth Beans',
       'orange', 'Ground Nut', 'Coffee', 'millet', 'mango', 'Sugarcane',
       'maize', 'banana', 'Coconut', 'rice', 'Kidney Beans', 'rice',
       'maize', 'Kidney Beans', 'grapes', 'Kidney Beans', 'Kidney Beans',
       'Tobacco', 'wheat', 'apple', 'muskmelon', 'Rubber', 'mango',
       'Chickpea', 'Adzuki Beans', 'Black gram', 'Peas', 'watermelon',
       'orange', 'papaya', 'Lentil', 'Tobacco', 'apple', 'muskmelon',
       'Ground Nut', 'pomegranate', 'watermelon', 'mango', 'Black gram',
       'Coffee', 'banana', 'mango', 'Peas', 'pomegranate', 'Coffee',
       'Sugarcane', 'pomegranate', 'Moth Beans', 'Coconut', 'Black gram',
       'muskmelon', 'Chickpea', 'Sugarcane', 'Mung Bean', 'Kidney Beans',
       'rice', 'Chickpea', 'Black gram', 'wheat', 'Rubber', 'mango',
       'Peas', 'mango', 'Peas', 'grapes', 'Coffee', 'Mung Bean',
       'Pigeon Peas', 'Lentil', 'Kidney Beans', 'Moth Beans', 'Jute',
       'Kidney Beans', 'banana', 'Pigeon Peas', 'Peas', 'Tea', 'Peas',
       'Moth Beans', 'muskmelon', 'Tea', 'Adzuki Beans', 'maize',
       'Lentil', 'rice', 'apple', 'Pigeon Peas', 'Mung Bean', 'papaya',
       'Adzuki Beans', 'Sugarcane', 'papaya', 'Adzuki Beans', 'apple',
       'papaya', 'papaya', 'Peas', 'Rubber', 'Mung Bean', 'Adzuki Beans',
       'rice', 'Sugarcane', 'Peas', 'Adzuki Beans', 'apple', 'Sugarcane',
       'maize', 'Black gram', 'millet', 'Chickpea', 'Mung Bean',
       'Mung Bean', 'Mung Bean', 'Ground Nut', 'Lentil', 'muskmelon',
       'Black gram', 'Coffee', 'Mung Bean', 'Pigeon Peas', 'millet',
       'Coconut', 'grapes', 'Pigeon Peas', 'watermelon', 'Coconut',
       'banana', 'Adzuki Beans', 'Coffee', 'Tobacco', 'Tea', 'millet',
       'millet', 'muskmelon', 'Chickpea', 'orange', 'papaya', 'maize',
       'papaya', 'banana', 'Chickpea', 'Adzuki Beans', 'rice', 'rice',
       'Tobacco', 'Chickpea', 'rice', 'Black gram', 'orange', 'orange',
       'wheat', 'orange', 'Chickpea', 'millet', 'Moth Beans',
       'Moth Beans', 'Ground Nut', 'Coffee', 'Tobacco', 'banana', 'mango',
       'Tea', 'wheat', 'Tea', 'Black gram', 'Moth Beans', 'wheat',
       'banana', 'Lentil', 'papaya', 'mango', 'Black gram', 'Peas',
       'apple', 'Coffee', 'Jute', 'pomegranate', 'Jute', 'Jute', 'wheat',
       'pomegranate', 'wheat', 'Moth Beans', 'Kidney Beans', 'Tobacco',
       'Lentil', 'Moth Beans', 'Sugarcane', 'orange', 'mango', 'Rubber',
       'banana', 'grapes', 'banana', 'watermelon', 'orange', 'Coffee',
       'banana', 'Coffee', 'Jute', 'Jute', 'Cotton', 'muskmelon',
       'Coffee', 'apple', 'Ground Nut', 'maize', 'Chickpea', 'Jute',
       'Mung Bean', 'Tobacco', 'Tobacco', 'Ground Nut', 'apple', 'wheat',
       'Moth Beans', 'Coconut', 'Chickpea', 'Ground Nut', 'rice',
       'orange', 'Lentil', 'mango', 'muskmelon', 'pomegranate', 'maize',
       'grapes', 'Adzuki Beans', 'millet', 'Tobacco', 'mango', 'Coffee',
       'Kidney Beans', 'Jute', 'Chickpea', 'Lentil', 'Adzuki Beans',
       'Cotton', 'Black gram', 'papaya', 'Adzuki Beans', 'Jute', 'banana',
       'Ground Nut', 'Chickpea', 'apple', 'watermelon', 'Adzuki Beans',
       'Cotton', 'papaya', 'orange', 'Coffee', 'Black gram', 'mango',
       'Coconut', 'Ground Nut', 'Cotton', 'Cotton', 'mango', 'mango',
       'millet', 'pomegranate', 'Adzuki Beans', 'Sugarcane', 'orange',
       'millet', 'Mung Bean', 'wheat', 'millet', 'Tea', 'Chickpea',
       'Coffee', 'Coconut', 'Sugarcane', 'Peas', 'Sugarcane', 'grapes',
       'pomegranate', 'orange', 'wheat', 'Kidney Beans', 'orange', 'rice',
       'Peas', 'grapes', 'muskmelon', 'Moth Beans', 'Kidney Beans', 'Tea',
       'Moth Beans', 'Lentil', 'Tobacco', 'Sugarcane', 'Black gram',
       'banana', 'banana', 'mango', 'Coffee', 'mango', 'Peas',
       'Kidney Beans', 'millet', 'Tobacco', 'Rubber', 'Rubber', 'rice',
       'orange', 'apple', 'orange', 'maize', 'Coffee', 'maize', 'Jute',
       'Mung Bean', 'pomegranate', 'Sugarcane', 'apple', 'Sugarcane',
       'watermelon', 'mango', 'mango', 'mango', 'Mung Bean', 'Tobacco',
       'apple', 'Cotton', 'maize', 'banana'], dtype=object)

In [39]:
y_test

873      Coffee
924      Cotton
386         Tea
692      Lentil
2333     grapes
         ...
1446    Tobacco
2453      apple
2396     grapes
572       maize
2251     banana
Name: label, Length: 775, dtype: object

### Evaluation

In [37]:
from sklearn.metrics import accuracy_score, f1_score, classification_report

In [27]:
print(accuracy_score(y_test,lr_pred))

0.9496774193548387

In [28]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

Adzuki Beans       1.00      1.00      1.00        25
  Black gram       1.00      0.96      0.98        25
    Chickpea       1.00      1.00      1.00        25
     Coconut       1.00      1.00      1.00        25
      Coffee       0.93      1.00      0.96        25
      Cotton       0.96      1.00      0.98        25
  Ground Nut       0.92      0.92      0.92        25
        Jute       0.95      0.84      0.89        25
Kidney Beans       1.00      1.00      1.00        25
      Lentil       0.93      1.00      0.96        25
  Moth Beans       0.88      0.88      0.88        25
   Mung Bean       1.00      1.00      1.00        25
        Peas       1.00      1.00      1.00        25
 Pigeon Peas       1.00      0.72      0.84        25
      Rubber       1.00      1.00      1.00        25
   Sugarcane       0.88      0.88      0.88        25
         Tea       1.00      1.00      1.00        25
     Tobacco       1.00      1.00      1.00        25
       apple       0.92      0.92      0.92        25
      banana       0.89      1.00      0.94        25
      grapes       1.00      0.96      0.98        25
       maize       0.92      0.88      0.90        25
       mango       0.83      1.00      0.91        25
      millet       1.00      1.00      1.00        25
   muskmelon       1.00      1.00      1.00        25
      orange       0.80      0.96      0.87        25
      papaya       1.00      0.88      0.94        25
 pomegranate       0.96      0.88      0.92        25
        rice       0.96      0.96      0.96        25
  watermelon       1.00      1.00      1.00        25
       wheat       0.80      0.80      0.80        25

    accuracy                           0.95       775
   macro avg       0.95      0.95      0.95       775
weighted avg       0.95      0.95      0.95       775

In [29]:
pd.crosstab(y_test,lr_pred)

col_0,Adzuki Beans,Black gram,Chickpea,Coconut,Coffee,Cotton,Ground Nut,Jute,Kidney Beans,Lentil,...,maize,mango,millet,muskmelon,orange,papaya,pomegranate,rice,watermelon,wheat
label,,,,,,,,,,,,,,,,,,,,,
Adzuki Beans,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Black gram,0,24,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Chickpea,0,0,25,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Coconut,0,0,0,25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Coffee,0,0,0,0,25,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cotton,0,0,0,0,0,25,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ground Nut,0,0,0,0,0,0,23,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Jute,0,0,0,0,0,0,0,21,0,0,...,0,0,0,0,0,0,0,1,0,0
Kidney Beans,0,0,0,0,0,0,0,0,25,0,...,0,0,0,0,0,0,0,0,0,0
Lentil,0,0,0,0,0,0,0,0,0,25,...,0,0,0,0,0,0,0,0,0,0
Moth Beans,0,0,0,0,0,0,0,0,0,2,...,1,0,0,0,0,0,0,0,0,0
Mung Bean,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Peas,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pigeon Peas,0,0,0,0,0,0,1,0,0,0,...,0,3,0,0,0,0,0,0,0,3
Rubber,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Sugarcane,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tea,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tobacco,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
apple,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
banana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
grapes,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
maize,0,0,0,0,0,0,0,0,0,0,...,22,0,0,0,0,0,0,0,0,2
mango,0,0,0,0,0,0,0,0,0,0,...,0,25,0,0,0,0,0,0,0,0
millet,0,0,0,0,0,0,0,0,0,0,...,0,0,25,0,0,0,0,0,0,0
muskmelon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,25,0,0,0,0,0,0
orange,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,24,0,1,0,0,0
papaya,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,22,0,0,0,0
pomegranate,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,22,0,0,0
rice,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,24,0,0
watermelon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,25,0
wheat,0,0,0,0,2,0,1,0,0,0,...,0,2,0,0,0,0,0,0,0,20